### ISSUE TITLE
BUG Report

### ISSUE THREAD

**Issue by xtayaitak** [yanwei1983/luatinkerE#10]
当用lua_tiinker<void>call(L,"Run")  假如实际没有向LUA中注册Run函数时。会发生内存泄漏。最后导致堆溢出或崩溃。
测试代码如下：
`int main()
{

	lua_State* L = luaL_newstate();
	luaL_openlibs(L);
	lua_tinker::init(L);

	//lua_tinker::call<void> 调用一个没能注册函数，lua stack会一直上升。直到崩溃

	int top = lua_gettop(L);

	for (int i = 0; i < 10000000; i++)
	{
		std::cout <<"before:" << lua_gettop(L) << std::endl;
		lua_tinker::call<void>(L, "Run");
		std::cout <<"after :" << lua_gettop(L) << std::endl;
	}

	return 0;
}`

**Comment by yanwei1983** [comment]
fixed
