### ISSUE TITLE
string _read 问题

### ISSUE THREAD

**Issue by dou1984** [yanwei1983/luatinkerE#13]
你好，有幸使用到luatinkerE，在开发的时候遇到一个lua_tostring问题,请看一下是否bug：

std::string lua_tinker::detail::_stack_help<std::string>::_read(lua_State *L, int index)
{
       //const char* strLua = lua_tostring(L,index,);
	int len = 0;
	const char* strLua = lua_tolstring(L,index, &len);
        ...

**Comment by yanwei1983** [comment]
不明白你的问题，
