### ISSUE TITLE
注册类成员函数时..如果成员函数返回值为const..是否不支持?

### ISSUE THREAD

**Issue by tangyu1018** [yanwei1983/luatinkerE#3]
例如有如下类
const ff test_v_ffv()
{
	std::cout << "test_v_ffv" << std::endl;
	return g_ff;
}

注册时报错
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2440	“初始化”: 无法从“const ff *”转换为“void *”	luatinkerE

**Comment by yanwei1983** [comment]
对 除了特化的版本之外 只能针对T T& t*
一般情况下我们只用 T* 否则会产生一次对象拷贝

**Comment by tangyu1018** [comment]
返回常量其实大多数时候是保证自己对这个返回值不做修改，口否有办法支持const的拷贝呢？

**Comment by tangyu1018** [comment]
实际上我是想
const ff& test_v_ffv()
{
std::cout << "test_v_ffv" << std::endl;
return g_ff;
}

**Comment by yanwei1983** [comment]
已经支持，但是请小心，因为对象导出到lua时，会丢失const限定符
const ff& test_v_ffv();
lua:
local const_ff = test_v_ffv();
const_ff:modify_ff_member(); --允许，因为已经丢失限定符

因为类成员函数导出到lua时，已经将const限定符擦除，也就是说非const对象也可以调用const成员函数

**Comment by yanwei1983** [comment]
义宏 LUATINKER_USERDATA_CHECK_CONST 将会储存const信息(bool)到userdata中，当调用成员函数时会检查是否允许调用,同时read是会检查是否发生丢失常量限定符的问题
