### ISSUE TITLE
注册子类成员函数时..如果该成员函数为父类所有..则编译报错

### ISSUE THREAD

**Issue by tangyu1018** [yanwei1983/luatinkerE#4]
例如如下类
class pppFoo
{
public:
	bool test1()
	{
		return false;
	}
};

class cccFoo :public pppFoo
{
public:
	bool test2()
	{
		return true;
	}
};

注册时:
	lua_tinker::class_add<cccFoo>(ls, "pppFoo", true);
	lua_tinker::class_con<cccFoo>(ls, lua_tinker::constructor<cccFoo>::invoke);
	lua_tinker::class_def<cccFoo>(ls, "test1", &cccFoo::test1);//此处报错
报错:
错误	C2825	'overload_functor': 当后面跟“::”时必须为类或命名空间	NFLuaScriptPlugin

**Comment by yanwei1983** [comment]
lua_tinker::class_add<pppFoo>(ls, "pppFoo", true);  //注册基类
lua_tinker::class_add<cccFoo>(ls, "cccFoo", true);   //注册派生类
lua_tinker::class_ini<cccFoo,pppFoo>(ls);  //注册派生关系

lua_tinker::class_con<cccFoo>(ls, lua_tinker::constructor<cccFoo>::invoke); //注册构造函数，如果不需要在lua构造，则不需要调用
lua_tinker::class_def<pppFoo>(ls, "test1", &pppFoo::test1) //注册基类函数
lua_tinker::class_def<cccFoo>(ls, "test2", &cccFoo::test2) //注册派生类函数

lua:
local foo = cccFoo();
foo:test2(); --call cccFoo::test2
foo:test1();--call pppFoo::test2

**Comment by tangyu1018** [comment]
这样能通过编译。。但lua脚本报错
can't convert argument 1 to class pppFoo

**Comment by tangyu1018** [comment]
其实我注释掉这段代码。。我之前的代码就可以直接编译并lua不报错
	template<typename T, typename overload_functor>
	void _class_def(lua_State* L, overload_functor&& functor)
	{
		new(lua_newuserdata(L, sizeof(overload_functor))) overload_functor(std::move(functor));
		//register metatable for gc
		{
			lua_newtable(L);
			lua_pushstring(L, "__gc");
			lua_pushcclosure(L, &destroyer<overload_functor>, 0);
			lua_rawset(L, -3);

			lua_setmetatable(L, -2);
		}
		lua_pushcclosure(L, &overload_functor::invoke_function, 1);
	}
这个跟重载有什么关系？

**Comment by yanwei1983** [comment]
对这是一个错误，我把m_type_idx放到了UserDataWarp里
这样派生类指针到基类指针的强制转换被 误判了

**Comment by yanwei1983** [comment]
实际上，你的注册错误是这样的
lua_tinker::class_def<cccFoo>(ls, "test1", &cccFoo::test1)
cccFoo::test1 的类型是 R(pppFOO::*)(ARGS...)
而class_def需要的是一个R(cccFOO::*)(ARGS...)

**Comment by tangyu1018** [comment]
但是继承类调用基类成员函数是正确的吧？
