### ISSUE TITLE
无法导出有这样参数的函数：`const std::vector<int>&` 

### ISSUE THREAD

**Issue by dourgulf** [yanwei1983/luatinkerE#9]
对于一个这样签名的函数：
std::string vector_join_const(const std::vector<int>& vec, const char* sep=',');
无法正确导出。导出的语法编译没有问题，但是，执行的时候，闭包函数式空指针。
理论上，const reference的参数类型应该和值类型参数一样可以导出
初步看是这里做了限制：
		//stl container T
		template<typename T>
		struct _stack_help<T, typename std::enable_if<!std::is_reference<T>::value && !std::is_pointer<T>::value && is_container<base_type<T>>::value>::type>

我尝试了一下放开第一个限制，但是这样子会有很多编译报错。需要再深入看看。
看看作者有没有什么思路？

**Comment by dourgulf** [comment]
补充：`执行的时候，闭包函数式空指针`这个情况有误。是我忘记了执行lua_tinker::init(L);执行了这个init之后，会看到有lua的执行报错：Can't convert argument 1 to class.

**Comment by yanwei1983** [comment]
参见 test_lua_vec1 , 没有发现任何问题

**Comment by yanwei1983** [comment]
我大概明白你的意思了， vector是不能转换为const vector的, 这是因为vector 导出到lua中会变成table， 而再从table输入到c++会产生性能损耗， 所以 只能从c++向lua写一个const vector ， 然后再从lua读一个const vector， 这个在内部，实际上是一个指针传递，基本上没有损耗

**Comment by yanwei1983** [comment]
vector fun1();
const vector& fun1_const();
void fun2(vector a);
void func2(const vector& a);


inlua:
local vec = fun1();    --vec = table
local vec_const = fun1_const(); --vec_const = user_data = ptr
fun2(vec); --succ, table->vec
fun2_const(vec_const); --succ user_data->user_data

**Comment by dourgulf** [comment]
我描述的可能不够清晰，我重新描述一下，我期望的导出情况是这样的：
```C++
#include "lua_tinker.h"
#include <string>
#include <vector>

std::string join_vector(const std::vector<int>& vec, const char* sep = ",")
{
	std::string result;
	for (size_t i=0; i<vec.size(); i++)
	{
		char buf[64];
		if (i>0)
		{
			snprintf(buf, sizeof(buf) - 1, "%s%d", sep, vec[i]);
		}
		else
		{
			snprintf(buf, sizeof(buf) - 1, "%d", vec[i]);
		}
		result += buf;
	}
	return result;
}

int main()
{
	lua_State* L = luaL_newstate();
	luaL_openlibs(L);
	lua_tinker::init(L);
	lua_tinker::def(L, "test", join_vector, ",");
	lua_tinker::dostring(L, "a = {1,2,3}; s1 = test(a); print(s1);");
    return 0;
}
```
按照目前的设计，正如你上一个答复里说的，参数类型const std::vector<int>& 会被模板识别成`userdata`
而，我期待的是被识别成stl容器。

**Comment by yanwei1983** [comment]
按照现在的设计，一个lua的table是不允许被转换为一个const vector&的， 只能转换为vector
而const vector&,只能从c++传递给lua， lua自己是无法生成const vector&的

```
std::string join_vector(std::vector<int> vec, const char* sep = ",") 这样是可以的
或者你需要
const vector<int>& push_vector_const_to_lua();
local a = push_vector_const_to_lua();
local str = join_vector(a,",");

```

**Comment by dourgulf** [comment]
当然，为了这个目的，我对join_vector做一个包装函数：
```C++
std::string join_vector_lua(std::vector<int> vec, const char* sep = ",")
{
	return join_vector(vec, sep);
}
```
然后，`lua_tinker::def(L, "test", join_vector_lua, ",");`；这样子，模板就能把参数识别成stl容器了。
这里，我的疑问是：
1. 能否去掉这样的包装，直接使用const std::vector&的参数形式来导出到LUA？
我尝试了一下把
```
struct _stack_help<T, typename std::enable_if<!std::is_reference<T>::value && 
```
这里的第一个`is_reference`判断条件去掉，配合`_readfromtable`的一些类型信息做了一些修改。
能针对这个类型，正确的识别成stl容器了。
但是，我对`_readfromtable`的修改，又使得，对map和set的识别不正确。
修改还未成功
2. 参数按值方式传递，是不是有容器的拷贝了？

**Comment by dourgulf** [comment]
嗯，是的，按照设计是不能这样的。
我们是否可以探讨一下这个设计限制是为什么呢？

**Comment by dourgulf** [comment]
我的理解是：如果是说转换成`std::vector&`的话，就有可能存在语义实现不正确的情况，C++可能修改参数，期望返回给lua，实际上做不到。
但是，把一个lua的table转换成`const std::vector&`应该是可以的，它和转换成`std::vector`值应该是语义一致的。

**Comment by dourgulf** [comment]
关于第二个疑问“参数按值方式传递，是不是有容器的拷贝了”，从LUA到C++层的table到vector的拷贝过程，应该是无法避免的。关键的地方在于，当table复制到vector之后，把vector传递给join_vector是否也存在内存拷贝。我跟踪调试一下，再最终invoke函数的时候，所有的参数都被转换成了左值
```
	template< class F, class... ArgTypes >
	auto invoke(F&& f, ArgTypes&&... args)
		// exception specification for QoI
		noexcept(noexcept(detail::INVOKE(std::forward<F>(f), std::forward<ArgTypes>(args)...)))
		-> decltype(detail::INVOKE(std::forward<F>(f), std::forward<ArgTypes>(args)...))
	{
		return detail::INVOKE(std::forward<F>(f), std::forward<ArgTypes>(args)...);
	}
```
从这个转换来看，实参应该是直接被move传递进函数，似乎没有进一步的拷贝发生。我没有想到一个简单的测试用例可以验证这一点。

**Comment by yanwei1983** [comment]
将stl容器的const版本，特意设置为user_data的方式传递的主要原因是性能
当我们在c++中使用const&时， 其本质就是传递一个指针，而不是值拷贝， 如果在使用的过程中，因为要转换成table，而导致多次转换，其效率是难以接受的（c++->lua一次， lua->c++又需要一次)

很多时候在lua代码中，我们只是想要将c++某个函数的返回值，传递给另外一个c++函数，比如
```
void send_msg_to(const vector<uint64_t>& idList, cmd, msg);
const vector<uint64_t>& void GetAllPlayerSetRef();
inlua:
send_msg_to(pScene:GetAllPlayerSetRef(), cmd, msg);

```
这样，其实是没有什么性能问题的，但是如果强行转换为 table, 而再lua中又不需要访问这个table，那么性能损失是巨大的， 所以当时就考虑，如果是 stl的值类型， 那么单独允许其从转换为table，或者从table中转换出来

其实也可以，将stl容器全部使用user_data的模式而不允许从table转换， 单独写一系列辅助函数比如 
vec_to_table(const vector&)
vector table_to_vec()

也可以为stl容器专门写一套meta_table,实现__index,__newindex模仿table，从而达到在lua中访问stl容器的需求

**Comment by dourgulf** [comment]
哦，我明白了，你是希望把table到vector的这个过程的性能消耗也去掉。
那么，我的另一个疑问：
当const vector& 被处理成userdata的情况下，我需要做一些什么额外的操作才能正确的处理这个userdata？
因为，目前导出这样参数的函数的话，执行函数是要报错的。

**Comment by yanwei1983** [comment]
也就是说，暂时没有办法，从lua代码中，将一个table转换为const vector&, 只能从c++中传递给lua

**Comment by yanwei1983** [comment]
因为func(const vector<int>&) 被invoke的时候，
会调用 read<const vector<int>&>
然后调用stack_help<const vector<int>&>::read(), 这个函数的返回值必须是const vector<int>& 而不能是vector<int>

**Comment by dourgulf** [comment]
基本明白设计的来龙去脉了，多谢指教~
